//action Types

export const FETCH_NOTES_PENDING='FETCH_NOTES_PENDING';
export const FETCH_NOTES_FULFILLED='FETCH_NOTES_FULFILLED';
export const FETCH_NOTES_REJECTED='FETCH_NOTES_REJECTED';

export const CREATE_NOTE_PENDING='CREATE_NOTE_PENDING';
export const CREATE_NOTE_FULFILLED='CREATE_NOTE_FULFILLED';
export const CREATE_NOTE_REJECTED='CREATE_NOTE_REJECTED';

export const UPDATE_NOTE_PENDING='UPDATE_NOTE_PENDING';
export const UPDATE_NOTE_FULFILLED='UPDATE_NOTE_FULFILLED';
export const UPDATE_NOTE_REJECTED='UPDATE_NOTE_REJECTED';

export const DELETE_NOTE_PENDING='DELETE_NOTE_PENDING';
export const DELETE_NOTE_FULFILLED='DELETE_NOTE_FULFILLED';
export const DELETE_NOTE_REJECTED='DELETE_NOTE_REJECTED';